### ISSUE TITLE
Support nested CSS Module class references

### ISSUE THREAD

**Issue by calebjacob** [near/bos-web-engine#295]
Create the following component in the Sandbox:

```tsx
import s from './styles.module.css';

function MyComponent() {
  return (
    <div className={s.wrapper}>
      <p className={s.message}>Hello</p>
    </div>
  );
}

export default MyComponent as BWEComponent;
```

Add the following CSS:

```css
.wrapper {
  border: 1px solid red;

  &:hover {
    .message {
      color: green;
    }
  }
}

.message {
  color: red;
}
```

This does not work as expected (hovering the wrapper should turn the message green). This type of pattern is common in more complex use cases when using CSS Modules.

If we target all `p` tags instead of `.message`, we can get our desired behavior for the short term:

```css
.wrapper {
  border: 1px solid red;

  &:hover {
    p {
      color: green;
    }
  }
}

.message {
  color: red;
}
```

Integrating with something like Lightning CSS or Post CSS could potentially solve this: https://github.com/near/bos-web-engine/issues/280
